pipeline:
  build:
    image: golang:${GO_VERSION}
    # secrets: [ test_example ]
    # environment:
    #   - GOBIN=(pwd)/bin
    commands:
      # - echo $TEST_EXAMPLE
      # - go get -t -d -v ./...
      # - go install -v -o bin/hello-$GOOS-$GOARCH hello.go
      - go get github.com/jjneely/buckytools
      - cd $GOPATH/src/github.com/jjneely/buckytools
      - go install ./...
      - echo $GOPATH/bin
      - ls -lha $GOPATH/bin

  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files:
       - /go/bin/*
    when:
      event: tag

matrix:
  GO_VERSION:
    - latest

  # GOARCH:
  #   - 386
  #   - amd64

  # GOOS: 
  #   - darwin
  #   - linux
  #   - windows