workspace:
  base: /go
  path: src/github.com/wasilak/buckytools

pipeline:
  build:
    image: golang:${GO_VERSION}
    commands:
      - go get github.com/wasilak/buckytools
      - cd $GOPATH/src/github.com/wasilak/buckytools
      - go install ./...
      - find /go/bin -type f -exec mv {} {}-$GOOS-$GOARCH \;

  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files:
       - /go/bin/*
    when:
      event: tag

matrix:
  GOPATH:
    - /go

  GO_VERSION:
    - latest

  GOARCH:
    - amd64

  GOOS: 
    - linux
