---
kind: pipeline
name: matrix-1

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/wasilak/buckytools

steps:
- name: build
  pull: default
  image: golang:latest
  commands:
  - go get github.com/wasilak/buckytools
  - cd $GOPATH/src/github.com/wasilak/buckytools
  - go install ./...
  - "find /go/bin -type f -exec mv {} {}-$GOOS-$GOARCH \\;"

- name: github_release
  pull: default
  image: plugins/github-release
  settings:
    files:
      from_secret: ""
      value:
      - "/go/bin/*"
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  when:
    event:
    - tag

